name: benchmark

on:
  issue_comment:
    types: [created]

jobs:

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: xt0rted/slash-command-action@v1.1.0
        id: command
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: bench

      - run: |
          docker build -t bench .
          docker run -v $PWD:/work --rm bench bash -c 'cd /work && ./bench.sh'
        if: steps.command.outputs.command-name

      - name: Post multi-line comments
        if: steps.command.outputs.command-name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: https://api.github.com/repos/jiro4989/bench/issues/1/comments
        run: |
          find cases -name result.json |
            xargs cat |
            curl -X POST \
                 -H "Authorization: token ${GITHUB_TOKEN}" \
                 -d @- \
                 ${URL}

      - run: echo "end"
